// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeminarCore2.Data;

namespace SeminarCore2.Migrations
{
    [DbContext(typeof(MojContext))]
    [Migration("20210310021344_MockDataSeed")]
    partial class MockDataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SeminarCore2.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("Grad");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SeminarCore2.Models.Predbiljezba", b =>
                {
                    b.Property<int>("PredbiljezbaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .IsRequired();

                    b.Property<string>("BrojTelefona")
                        .IsRequired();

                    b.Property<DateTime>("Datum");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<int>("SeminarID");

                    b.Property<bool?>("StatusDaNe");

                    b.HasKey("PredbiljezbaID");

                    b.HasIndex("SeminarID");

                    b.ToTable("Predbiljezba");

                    b.HasData(
                        new
                        {
                            PredbiljezbaID = 1,
                            Adresa = "00065 Johnson Lane",
                            BrojTelefona = "6053905224",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bknoble0@indiegogo.com",
                            Ime = "Billie",
                            Prezime = "Knoble",
                            SeminarID = 5,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 2,
                            Adresa = "934 Northport Center",
                            BrojTelefona = "3157073929",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gzeale1@amazonaws.com",
                            Ime = "Georgena",
                            Prezime = "Zeale",
                            SeminarID = 7,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 3,
                            Adresa = "28274 Waxwing Circle",
                            BrojTelefona = "2085217617",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mduffield2@cargocollective.com",
                            Ime = "Mikol",
                            Prezime = "Duffield",
                            SeminarID = 8,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 4,
                            Adresa = "39111 Leroy Crossing",
                            BrojTelefona = "8165857024",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bbirks3@cdc.gov",
                            Ime = "Beau",
                            Prezime = "Birks",
                            SeminarID = 5,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 5,
                            Adresa = "45 Butternut Avenue",
                            BrojTelefona = "3341834111",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "atiffany4@slate.com",
                            Ime = "Alain",
                            Prezime = "Tiffany",
                            SeminarID = 9,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 6,
                            Adresa = "4536 Elmside Way",
                            BrojTelefona = "3676841030",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ttapsfield5@goodreads.com",
                            Ime = "Toddie",
                            Prezime = "Tapsfield",
                            SeminarID = 3,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 7,
                            Adresa = "713 Sutherland Avenue",
                            BrojTelefona = "1366201018",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bfernandes6@biglobe.ne.jp",
                            Ime = "Brenna",
                            Prezime = "Fernandes",
                            SeminarID = 4,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 8,
                            Adresa = "33 Amoth Pass",
                            BrojTelefona = "1625805625",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fbranney7@cnn.com",
                            Ime = "Faun",
                            Prezime = "Branney",
                            SeminarID = 1,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 9,
                            Adresa = "35243 Mcbride Alley",
                            BrojTelefona = "5205010980",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sbisp8@vk.com",
                            Ime = "Sandie",
                            Prezime = "Bisp",
                            SeminarID = 2,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 10,
                            Adresa = "35488 Riverside Alley",
                            BrojTelefona = "4625606776",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cmocquer9@phpbb.com",
                            Ime = "Cindy",
                            Prezime = "Mocquer",
                            SeminarID = 5,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 11,
                            Adresa = "07 Bluejay Hill",
                            BrojTelefona = "4323400386",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gmacilhaggaa@umn.edu",
                            Ime = "Garrett",
                            Prezime = "MacIlhagga",
                            SeminarID = 3,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 12,
                            Adresa = "10974 Dakota Circle",
                            BrojTelefona = "3381321862",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sfoskenb@opensource.org",
                            Ime = "Steve",
                            Prezime = "Fosken",
                            SeminarID = 4,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 13,
                            Adresa = "2198 Logan Terrace",
                            BrojTelefona = "1069173520",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kgueinnc@amazon.co.uk",
                            Ime = "Kim",
                            Prezime = "Gueinn",
                            SeminarID = 4,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 14,
                            Adresa = "68 Hovde Center",
                            BrojTelefona = "2946340613",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lveard@ycombinator.com",
                            Ime = "Leonard",
                            Prezime = "Vear",
                            SeminarID = 1,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 15,
                            Adresa = "448 Merchant Drive",
                            BrojTelefona = "1125683489",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mbenziese@networkadvertising.org",
                            Ime = "Michail",
                            Prezime = "Benzies",
                            SeminarID = 9,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 16,
                            Adresa = "3637 Bluejay Alley",
                            BrojTelefona = "9492511661",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sgittoesf@foxnews.com",
                            Ime = "Sebastiano",
                            Prezime = "Gittoes",
                            SeminarID = 6,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 17,
                            Adresa = "6375 Dennis Trail",
                            BrojTelefona = "7632981138",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kcassyg@paypal.com",
                            Ime = "Konstantine",
                            Prezime = "Cassy",
                            SeminarID = 1,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 18,
                            Adresa = "73926 Morrow Junction",
                            BrojTelefona = "7174787707",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kpeckitth@addthis.com",
                            Ime = "Kacie",
                            Prezime = "Peckitt",
                            SeminarID = 9,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 19,
                            Adresa = "5050 New Castle Center",
                            BrojTelefona = "2373518447",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nsteedeni@berkeley.edu",
                            Ime = "Nanice",
                            Prezime = "Steeden",
                            SeminarID = 3,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 20,
                            Adresa = "247 Acker Street",
                            BrojTelefona = "4784773033",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ssapwellj@naver.com",
                            Ime = "Silvan",
                            Prezime = "Sapwell",
                            SeminarID = 6,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 21,
                            Adresa = "63 Sachs Place",
                            BrojTelefona = "3368486646",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cclosek@typepad.com",
                            Ime = "Coriss",
                            Prezime = "Close",
                            SeminarID = 5,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 22,
                            Adresa = "7211 Manufacturers Plaza",
                            BrojTelefona = "5703106587",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cdumsdayl@ftc.gov",
                            Ime = "Casper",
                            Prezime = "Dumsday",
                            SeminarID = 9,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 23,
                            Adresa = "02 Garrison Circle",
                            BrojTelefona = "1767584765",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cforsythem@aol.com",
                            Ime = "Claiborn",
                            Prezime = "Forsythe",
                            SeminarID = 3,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 24,
                            Adresa = "5179 Cordelia Drive",
                            BrojTelefona = "9482592137",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jedelmannn@google.pl",
                            Ime = "Julian",
                            Prezime = "Edelmann",
                            SeminarID = 4,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 25,
                            Adresa = "50 Carberry Court",
                            BrojTelefona = "8316387384",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ejustiso@php.net",
                            Ime = "Earl",
                            Prezime = "Justis",
                            SeminarID = 2,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 26,
                            Adresa = "75 Montana Center",
                            BrojTelefona = "5316710291",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hgulbergp@meetup.com",
                            Ime = "Hana",
                            Prezime = "Gulberg",
                            SeminarID = 9,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 27,
                            Adresa = "9 Pierstorff Avenue",
                            BrojTelefona = "3327893290",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adanettq@mtv.com",
                            Ime = "Augustus",
                            Prezime = "Danett",
                            SeminarID = 8,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 28,
                            Adresa = "92 Bayside Center",
                            BrojTelefona = "3577232352",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ksimpkissr@mashable.com",
                            Ime = "Kippy",
                            Prezime = "Simpkiss",
                            SeminarID = 5,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 29,
                            Adresa = "33 Sunfield Avenue",
                            BrojTelefona = "4313662073",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "egormans@dot.gov",
                            Ime = "Eugenius",
                            Prezime = "Gorman",
                            SeminarID = 4,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 30,
                            Adresa = "71341 Kings Place",
                            BrojTelefona = "8106137485",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dlukasent@youtu.be",
                            Ime = "Doug",
                            Prezime = "Lukasen",
                            SeminarID = 1,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 31,
                            Adresa = "107 Banding Point",
                            BrojTelefona = "3786824935",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "brattenburyu@statcounter.com",
                            Ime = "Benito",
                            Prezime = "Rattenbury",
                            SeminarID = 5,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 32,
                            Adresa = "743 Straubel Alley",
                            BrojTelefona = "3229957926",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rbellamv@chicagotribune.com",
                            Ime = "Read",
                            Prezime = "Bellam",
                            SeminarID = 6,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 33,
                            Adresa = "1 Waubesa Road",
                            BrojTelefona = "5782652578",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "umossw@biblegateway.com",
                            Ime = "Ursala",
                            Prezime = "Moss",
                            SeminarID = 6,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 34,
                            Adresa = "7 Twin Pines Way",
                            BrojTelefona = "2108940577",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fmalamorex@amazon.com",
                            Ime = "Fifine",
                            Prezime = "Malamore",
                            SeminarID = 7,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 35,
                            Adresa = "09504 Goodland Plaza",
                            BrojTelefona = "5071818282",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "giianony@imgur.com",
                            Ime = "Gene",
                            Prezime = "Iianon",
                            SeminarID = 3,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 36,
                            Adresa = "047 Commercial Way",
                            BrojTelefona = "3889400373",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fhackingez@rambler.ru",
                            Ime = "Fransisco",
                            Prezime = "Hackinge",
                            SeminarID = 6,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 37,
                            Adresa = "339 Hintze Court",
                            BrojTelefona = "8039343366",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "icrab10@springer.com",
                            Ime = "Ives",
                            Prezime = "Crab",
                            SeminarID = 1,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 38,
                            Adresa = "3 Birchwood Lane",
                            BrojTelefona = "4971198302",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "plunam11@blinklist.com",
                            Ime = "Pru",
                            Prezime = "Lunam",
                            SeminarID = 1,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 39,
                            Adresa = "581 Gina Park",
                            BrojTelefona = "1609554358",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "npiquard12@1und1.de",
                            Ime = "Noak",
                            Prezime = "Piquard",
                            SeminarID = 5,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 40,
                            Adresa = "46860 Morrow Plaza",
                            BrojTelefona = "8699322796",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mderyebarrett13@gov.uk",
                            Ime = "Morten",
                            Prezime = "Derye-Barrett",
                            SeminarID = 4,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 41,
                            Adresa = "53 Mifflin Place",
                            BrojTelefona = "2287803132",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mbilston14@census.gov",
                            Ime = "Marja",
                            Prezime = "Bilston",
                            SeminarID = 9,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 42,
                            Adresa = "9 Parkside Lane",
                            BrojTelefona = "2704108843",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "glutty15@comcast.net",
                            Ime = "Guillemette",
                            Prezime = "Lutty",
                            SeminarID = 3,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 43,
                            Adresa = "1 Elka Pass",
                            BrojTelefona = "2861855460",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mmacgrath16@globo.com",
                            Ime = "Maddalena",
                            Prezime = "MacGrath",
                            SeminarID = 6,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 44,
                            Adresa = "90395 Corry Park",
                            BrojTelefona = "3091914190",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jbeaney17@livejournal.com",
                            Ime = "Julia",
                            Prezime = "Beaney",
                            SeminarID = 3,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 45,
                            Adresa = "5368 Ilene Pass",
                            BrojTelefona = "3428099573",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tlanger18@dell.com",
                            Ime = "Tresa",
                            Prezime = "Langer",
                            SeminarID = 7,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 46,
                            Adresa = "85703 Oak Valley Circle",
                            BrojTelefona = "3374592419",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "gwolfit19@ft.com",
                            Ime = "Garek",
                            Prezime = "Wolfit",
                            SeminarID = 6,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 47,
                            Adresa = "7 Charing Cross Junction",
                            BrojTelefona = "2439852536",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "krashleigh1a@fda.gov",
                            Ime = "Kit",
                            Prezime = "Rashleigh",
                            SeminarID = 5,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 48,
                            Adresa = "23776 Forest Run Crossing",
                            BrojTelefona = "6337918303",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mvink1b@weibo.com",
                            Ime = "Melvin",
                            Prezime = "Vink",
                            SeminarID = 5,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 49,
                            Adresa = "848 Fisk Trail",
                            BrojTelefona = "6532773069",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hroulston1c@ebay.co.uk",
                            Ime = "Hamid",
                            Prezime = "Roulston",
                            SeminarID = 2,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 50,
                            Adresa = "20568 Northridge Hill",
                            BrojTelefona = "7979792847",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "erubinowitch1d@epa.gov",
                            Ime = "Elfie",
                            Prezime = "Rubinowitch",
                            SeminarID = 2,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 51,
                            Adresa = "97 Lawn Plaza",
                            BrojTelefona = "8404724615",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cweavers1e@salon.com",
                            Ime = "Cornela",
                            Prezime = "Weavers",
                            SeminarID = 8,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 52,
                            Adresa = "61227 Hanover Parkway",
                            BrojTelefona = "4819326272",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tgiacovelli1f@nbcnews.com",
                            Ime = "Tasia",
                            Prezime = "Giacovelli",
                            SeminarID = 5,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 53,
                            Adresa = "58 Bowman Court",
                            BrojTelefona = "6945479897",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lfishbourn1g@histats.com",
                            Ime = "Linda",
                            Prezime = "Fishbourn",
                            SeminarID = 2,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 54,
                            Adresa = "03331 Pankratz Center",
                            BrojTelefona = "9813727144",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jgiordano1h@liveinternet.ru",
                            Ime = "Jobina",
                            Prezime = "Giordano",
                            SeminarID = 3,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 55,
                            Adresa = "75 Maryland Avenue",
                            BrojTelefona = "7349551843",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "shabard1i@microsoft.com",
                            Ime = "Sherye",
                            Prezime = "Habard",
                            SeminarID = 6,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 56,
                            Adresa = "516 Anniversary Junction",
                            BrojTelefona = "8938504375",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ekingsland1j@privacy.gov.au",
                            Ime = "Elianore",
                            Prezime = "Kingsland",
                            SeminarID = 4,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 57,
                            Adresa = "179 Thierer Terrace",
                            BrojTelefona = "5154100589",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jbilt1k@mac.com",
                            Ime = "Janene",
                            Prezime = "Bilt",
                            SeminarID = 1,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 58,
                            Adresa = "70 Randy Center",
                            BrojTelefona = "1027689813",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "afrankes1l@omniture.com",
                            Ime = "Arlan",
                            Prezime = "Frankes",
                            SeminarID = 2,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 59,
                            Adresa = "52674 Village Green Drive",
                            BrojTelefona = "2454513649",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tmckinless1m@hao123.com",
                            Ime = "Tonnie",
                            Prezime = "McKinless",
                            SeminarID = 8,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 60,
                            Adresa = "06 Clarendon Crossing",
                            BrojTelefona = "6131033769",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mtourner1n@prlog.org",
                            Ime = "Mark",
                            Prezime = "Tourner",
                            SeminarID = 9,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 61,
                            Adresa = "1058 Arrowood Terrace",
                            BrojTelefona = "9758098743",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dglabach1o@boston.com",
                            Ime = "Diego",
                            Prezime = "Glabach",
                            SeminarID = 4,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 62,
                            Adresa = "0074 Thompson Parkway",
                            BrojTelefona = "4224994386",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tivanishin1p@usgs.gov",
                            Ime = "Talbot",
                            Prezime = "Ivanishin",
                            SeminarID = 4,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 63,
                            Adresa = "27444 Kensington Lane",
                            BrojTelefona = "9563403608",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bfairholm1q@over-blog.com",
                            Ime = "Barris",
                            Prezime = "Fairholm",
                            SeminarID = 5,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 64,
                            Adresa = "025 Ilene Center",
                            BrojTelefona = "1836791765",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hspink1r@google.de",
                            Ime = "Hillary",
                            Prezime = "Spink",
                            SeminarID = 3,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 65,
                            Adresa = "7 Kennedy Street",
                            BrojTelefona = "1661348024",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "goscanlan1s@stanford.edu",
                            Ime = "Glori",
                            Prezime = "O'Scanlan",
                            SeminarID = 9,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 66,
                            Adresa = "3339 Hauk Street",
                            BrojTelefona = "3186443831",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sriveles1t@ucoz.ru",
                            Ime = "Sonnie",
                            Prezime = "Riveles",
                            SeminarID = 5,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 67,
                            Adresa = "02 Rieder Circle",
                            BrojTelefona = "2616956274",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ashemwell1u@yahoo.com",
                            Ime = "Angie",
                            Prezime = "Shemwell",
                            SeminarID = 5,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 68,
                            Adresa = "22645 Cascade Terrace",
                            BrojTelefona = "6048667403",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mcoursor1v@a8.net",
                            Ime = "Minda",
                            Prezime = "Coursor",
                            SeminarID = 9,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 69,
                            Adresa = "2 Pond Trail",
                            BrojTelefona = "7283237979",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lskippen1w@liveinternet.ru",
                            Ime = "Lorrie",
                            Prezime = "Skippen",
                            SeminarID = 4,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 70,
                            Adresa = "8 Reinke Court",
                            BrojTelefona = "3101385311",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aorrin1x@harvard.edu",
                            Ime = "Angel",
                            Prezime = "Orrin",
                            SeminarID = 7,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 71,
                            Adresa = "8655 Marquette Plaza",
                            BrojTelefona = "3159185954",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amcgillivray1y@joomla.org",
                            Ime = "Alexander",
                            Prezime = "McGillivray",
                            SeminarID = 1,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 72,
                            Adresa = "15395 Garrison Place",
                            BrojTelefona = "6124121294",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bkulvear1z@github.io",
                            Ime = "Byron",
                            Prezime = "Kulvear",
                            SeminarID = 9,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 73,
                            Adresa = "5253 Raven Alley",
                            BrojTelefona = "2545970265",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mcritchlow20@ow.ly",
                            Ime = "Mickey",
                            Prezime = "Critchlow",
                            SeminarID = 9,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 74,
                            Adresa = "703 Lake View Circle",
                            BrojTelefona = "8803826876",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bbusst21@bravesites.com",
                            Ime = "Brnaby",
                            Prezime = "Busst",
                            SeminarID = 8,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 75,
                            Adresa = "1385 Harbort Center",
                            BrojTelefona = "3235671971",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dwildgoose22@weibo.com",
                            Ime = "Dov",
                            Prezime = "Wildgoose",
                            SeminarID = 1,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 76,
                            Adresa = "071 Mcguire Trail",
                            BrojTelefona = "4429101661",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "icosker23@adobe.com",
                            Ime = "Isidro",
                            Prezime = "Cosker",
                            SeminarID = 7,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 77,
                            Adresa = "24168 Laurel Trail",
                            BrojTelefona = "5941351824",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cmacglory24@blinklist.com",
                            Ime = "Candis",
                            Prezime = "MacGlory",
                            SeminarID = 4,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 78,
                            Adresa = "3 Melody Hill",
                            BrojTelefona = "5965196455",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "speterken25@vistaprint.com",
                            Ime = "Sabra",
                            Prezime = "Peterken",
                            SeminarID = 6,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 79,
                            Adresa = "59 Calypso Trail",
                            BrojTelefona = "9815221384",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jtailour26@dailymotion.com",
                            Ime = "Jeramey",
                            Prezime = "Tailour",
                            SeminarID = 1,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 80,
                            Adresa = "61 Arrowood Avenue",
                            BrojTelefona = "7714941396",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "solone27@weebly.com",
                            Ime = "Say",
                            Prezime = "O' Lone",
                            SeminarID = 1,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 81,
                            Adresa = "375 Garrison Trail",
                            BrojTelefona = "9782096552",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bburgwyn28@hp.com",
                            Ime = "Brigida",
                            Prezime = "Burgwyn",
                            SeminarID = 7,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 82,
                            Adresa = "16 Farwell Avenue",
                            BrojTelefona = "5681390743",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ftilston29@trellian.com",
                            Ime = "Fabe",
                            Prezime = "Tilston",
                            SeminarID = 2,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 83,
                            Adresa = "905 Nancy Place",
                            BrojTelefona = "6873159245",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hdarling2a@dell.com",
                            Ime = "Heath",
                            Prezime = "Darling",
                            SeminarID = 8,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 84,
                            Adresa = "0812 Loftsgordon Plaza",
                            BrojTelefona = "5261026496",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hgahagan2b@yolasite.com",
                            Ime = "Hiram",
                            Prezime = "Gahagan",
                            SeminarID = 5,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 85,
                            Adresa = "19629 Anderson Parkway",
                            BrojTelefona = "6653503024",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phammatt2c@oracle.com",
                            Ime = "Patricio",
                            Prezime = "Hammatt",
                            SeminarID = 3,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 86,
                            Adresa = "3041 Roth Court",
                            BrojTelefona = "8494210282",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jdargue2d@gnu.org",
                            Ime = "Jany",
                            Prezime = "Dargue",
                            SeminarID = 5,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 87,
                            Adresa = "90 Village Green Place",
                            BrojTelefona = "5579731320",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kspinello2e@bloomberg.com",
                            Ime = "Kimble",
                            Prezime = "Spinello",
                            SeminarID = 8,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 88,
                            Adresa = "9 Ridgeview Park",
                            BrojTelefona = "2218784429",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emcgaughey2f@seattletimes.com",
                            Ime = "Elva",
                            Prezime = "Mc Gaughey",
                            SeminarID = 6,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 89,
                            Adresa = "05214 Pine View Terrace",
                            BrojTelefona = "6265404835",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "svenneur2g@dyndns.org",
                            Ime = "Sean",
                            Prezime = "Venneur",
                            SeminarID = 4,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 90,
                            Adresa = "996 Michigan Trail",
                            BrojTelefona = "2466558471",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "msappson2h@marriott.com",
                            Ime = "Morrie",
                            Prezime = "Sappson",
                            SeminarID = 6,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 91,
                            Adresa = "7 Pankratz Circle",
                            BrojTelefona = "3157940297",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fcordaroy2i@kickstarter.com",
                            Ime = "Felizio",
                            Prezime = "Cordaroy",
                            SeminarID = 7,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 92,
                            Adresa = "6 Oxford Drive",
                            BrojTelefona = "7442823743",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chuyghe2j@rambler.ru",
                            Ime = "Celie",
                            Prezime = "Huyghe",
                            SeminarID = 2,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 93,
                            Adresa = "2 Duke Court",
                            BrojTelefona = "5891781168",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "adot2k@aboutads.info",
                            Ime = "Antony",
                            Prezime = "Dot",
                            SeminarID = 9,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 94,
                            Adresa = "0 Badeau Pass",
                            BrojTelefona = "8771001221",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oforkan2l@wunderground.com",
                            Ime = "Otto",
                            Prezime = "Forkan",
                            SeminarID = 1,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 95,
                            Adresa = "0447 Burning Wood Park",
                            BrojTelefona = "4052263142",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nmills2m@hatena.ne.jp",
                            Ime = "Neysa",
                            Prezime = "Mills",
                            SeminarID = 6,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 96,
                            Adresa = "3444 Vera Place",
                            BrojTelefona = "9543352672",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "abaden2n@baidu.com",
                            Ime = "Andre",
                            Prezime = "Baden",
                            SeminarID = 8,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 97,
                            Adresa = "64294 Chinook Point",
                            BrojTelefona = "7826172779",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pnowell2o@soundcloud.com",
                            Ime = "Prudence",
                            Prezime = "Nowell",
                            SeminarID = 1,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 98,
                            Adresa = "67570 Warrior Pass",
                            BrojTelefona = "8515944733",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mmathie2p@princeton.edu",
                            Ime = "Melosa",
                            Prezime = "Mathie",
                            SeminarID = 5,
                            StatusDaNe = false
                        },
                        new
                        {
                            PredbiljezbaID = 99,
                            Adresa = "0022 Lakewood Avenue",
                            BrojTelefona = "8301745124",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rgange2q@tripod.com",
                            Ime = "Roslyn",
                            Prezime = "Gange",
                            SeminarID = 9,
                            StatusDaNe = true
                        },
                        new
                        {
                            PredbiljezbaID = 100,
                            Adresa = "3 Ridgeview Crossing",
                            BrojTelefona = "5071896550",
                            Datum = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kkilius2r@sciencedaily.com",
                            Ime = "Kort",
                            Prezime = "Kilius",
                            SeminarID = 7,
                            StatusDaNe = false
                        });
                });

            modelBuilder.Entity("SeminarCore2.Models.Seminar", b =>
                {
                    b.Property<int>("SeminarID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("PopunjenDaNe");

                    b.HasKey("SeminarID");

                    b.ToTable("Seminar");

                    b.HasData(
                        new
                        {
                            SeminarID = 1,
                            Datum = new DateTime(1989, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "C#",
                            Opis = "Opis 1",
                            PopunjenDaNe = true
                        },
                        new
                        {
                            SeminarID = 2,
                            Datum = new DateTime(2005, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "Visual Basic",
                            Opis = "Opis 2",
                            PopunjenDaNe = false
                        },
                        new
                        {
                            SeminarID = 3,
                            Datum = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "Python",
                            Opis = "Opis 3",
                            PopunjenDaNe = true
                        },
                        new
                        {
                            SeminarID = 4,
                            Datum = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "C++",
                            Opis = "Opis 4",
                            PopunjenDaNe = false
                        },
                        new
                        {
                            SeminarID = 5,
                            Datum = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "Java",
                            Opis = "Opis 5",
                            PopunjenDaNe = false
                        },
                        new
                        {
                            SeminarID = 6,
                            Datum = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "Graphic Design",
                            Opis = "Opis 6",
                            PopunjenDaNe = false
                        },
                        new
                        {
                            SeminarID = 7,
                            Datum = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "Javescript & jQuery",
                            Opis = "Opis 7",
                            PopunjenDaNe = false
                        },
                        new
                        {
                            SeminarID = 8,
                            Datum = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "Angular",
                            Opis = "Opis 8",
                            PopunjenDaNe = false
                        },
                        new
                        {
                            SeminarID = 9,
                            Datum = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naziv = "Ruby",
                            Opis = "Opis 9",
                            PopunjenDaNe = false
                        });
                });

            modelBuilder.Entity("SeminarCore2.Models.Zaposlenik", b =>
                {
                    b.Property<int>("ZaposlenikID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Prezime");

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("ZaposlenikID");

                    b.ToTable("Zaposlenik");

                    b.HasData(
                        new
                        {
                            ZaposlenikID = -1,
                            Ime = "Ivan",
                            Password = "Admin",
                            Prezime = "Ivanic",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SeminarCore2.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SeminarCore2.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeminarCore2.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SeminarCore2.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SeminarCore2.Models.Predbiljezba", b =>
                {
                    b.HasOne("SeminarCore2.Models.Seminar", "Seminar")
                        .WithMany("Predbiljezbe")
                        .HasForeignKey("SeminarID")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
